# Project: Projeto2
# Makefile created by Dev-C++ 4.9.9.2

CPP  = g++.exe
CC   = gcc.exe
WINDRES = windres.exe
RES  = 
OBJ  = casr1.o $(RES)
LINKOBJ  = casr1.o $(RES)
LIBS =  -L"C:/Users/gabri/Downloads/Dev-Cpp/lib"  
INCS =  -I"C:/Users/gabri/Downloads/Dev-Cpp/include" 
CXXINCS =  -I"C:/Users/gabri/Downloads/Dev-Cpp/lib/gcc/mingw32/3.4.2/include"  -I"C:/Users/gabri/Downloads/Dev-Cpp/include/c++/3.4.2/backward"  -I"C:/Users/gabri/Downloads/Dev-Cpp/include/c++/3.4.2/mingw32"  -I"C:/Users/gabri/Downloads/Dev-Cpp/include/c++/3.4.2"  -I"C:/Users/gabri/Downloads/Dev-Cpp/include" 
BIN  = casr1.exe
CXXFLAGS = $(CXXINCS)  
CFLAGS = $(INCS)  
RM = rm -f

.PHONY: all all-before all-after clean clean-custom

all: all-before casr1.exe all-after


clean: clean-custom
	${RM} $(OBJ) $(BIN)

$(BIN): $(OBJ)
	$(CC) $(LINKOBJ) -o "casr1.exe" $(LIBS)

casr1.o: casr1.c
	$(CC) -c casr1.c -o casr1.o $(CFLAGS)
